import classNames from 'classnames';
import {useContext} from 'preact/hooks';

import {ConfigContext} from '/src/Common';
import './Icon.css';

const iconColors = [
  'white',
  'grey',
  'orange',
  'green',
  'purple',
  'aqua',
  'red',
  'yellow',
  'cyan',
];

// Icon colors that users can't really put to use
const hiddenColors = [
  'bright-green', // Used for sidebar button '+' icon
  'dark-grey', // Used for hero ability icons
  'item-spirit', // Used for the inner color of spirit item icons
  'item-vitality', // Used for the inner color of vitality item icons
  'item-weapon', // Used for the inner color of weapon item icons
];

// Map icon name to file
const filenames = {
  'item/basic_magazine':                  'item/basic_magazine.svg',
  'item/close_quarters':                  'item/close_quarters.svg',
  'item/headshot_booster':                'item/headshot_booster.svg',
  'item/high_velocity_mag':               'item/high_velocity_mag.svg',
  'item/hollow_point_ward':               'item/hollow_point_ward.svg',
  'item/monster_rounds':                  'item/monster_rounds.svg',
  'item/rapid_rounds':                    'item/rapid_rounds.svg',
  'item/restorative_shot':                'item/restorative_shot.svg',
  'item/active_reload':                   'item/active_reload.svg',
  'item/berserker':                       'item/berserker.svg',
  'item/fleetfoot':                       'item/fleetfoot.svg',
  'item/kinetic_dash':                    'item/kinetic_dash.svg',
  'item/long_range':                      'item/long_range.svg',
  'item/melee_charge':                    'item/melee_charge.svg',
  'item/mystic_shot':                     'item/mystic_shot.svg',
  'item/slowing_bullets':                 'item/slowing_bullets.svg',
  'item/soul_shredder_bullets':           'item/soul_shredder_bullets.svg',
  'item/swift_striker':                   'item/swift_striker.svg',
  'item/alchemical_fire':                 'item/alchemical_fire.svg',
  'item/burst_fire':                      'item/burst_fire.svg',
  'item/escalating_resilience':           'item/escalating_resilience.svg',
  'item/headhunter':                      'item/headhunter.svg',
  'item/heroic_aura':                     'item/heroic_aura.svg',
  'item/hunters_aura':                    'item/hunters_aura.svg',
  'item/intensifying_magazine':           'item/intensifying_magazine.svg',
  'item/point_blank':                     'item/point_blank.svg',
  'item/pristine_emblem':                 'item/pristine_emblem.svg',
  'item/sharpshooter':                    'item/sharpshooter.svg',
  'item/spellslinger_headshots':          'item/spellslinger_headshots.png',
  'item/tesla_bullets':                   'item/tesla_bullets.svg',
  'item/titanic_magazine':                'item/titanic_magazine.svg',
  'item/toxic_bullets':                   'item/toxic_bullets.svg',
  'item/warp_stone':                      'item/warp_stone.svg',
  'item/crippling_headshot':              'item/crippling_headshot.svg',
  'item/frenzy':                          'item/frenzy.svg',
  'item/glass_cannon':                    'item/glass_cannon.svg',
  'item/lucky_shot':                      'item/lucky_shot.svg',
  'item/ricochet':                        'item/ricochet.svg',
  'item/shadow_weave':                    'item/shadow_weave.svg',
  'item/silencer':                        'item/silencer.svg',
  'item/spiritual_overflow':              'item/spiritual_overflow.svg',
  'item/vampiric_burst':                  'item/vampiric_burst.svg',
  'item/enduring_spirit':                 'item/enduring_spirit.svg',
  'item/extra_health':                    'item/extra_health.svg',
  'item/extra_regen':                     'item/extra_regen.svg',
  'item/extra_stamina':                   'item/extra_stamina.svg',
  'item/healing_rite':                    'item/healing_rite.svg',
  'item/melee_lifesteal':                 'item/melee_lifesteal.svg',
  'item/sprint_boots':                    'item/sprint_boots.svg',
  'item/bullet_armor':                    'item/bullet_armor.svg',
  'item/bullet_lifesteal':                'item/bullet_lifesteal.svg',
  'item/combat_barrier':                  'item/combat_barrier.svg',
  'item/debuff_reducer':                  'item/debuff_reducer.svg',
  'item/divine_barrier':                  'item/divine_barrier.svg',
  'item/enchanters_barrier':              'item/enchanters_barrier.svg',
  'item/enduring_speed':                  'item/enduring_speed.svg',
  'item/healbane':                        'item/healbane.svg',
  'item/healing_booster':                 'item/healing_booster.svg',
  'item/healing_nova':                    'item/healing_nova.svg',
  'item/reactive_barrier':                'item/reactive_barrier.svg',
  'item/restorative_locket':              'item/restorative_locket.svg',
  'item/return_fire':                     'item/return_fire.svg',
  'item/spirit_armor':                    'item/spirit_armor.svg',
  'item/spirit_lifesteal':                'item/spirit_lifesteal.svg',
  'item/debuff_remover':                  'item/debuff_remover.svg',
  'item/fortitude':                       'item/fortitude.svg',
  'item/improved_bullet_armor':           'item/improved_bullet_armor.svg',
  'item/improved_spirit_armor':           'item/improved_spirit_armor.svg',
  'item/lifestrike':                      'item/lifestrike.svg',
  'item/majestic_leap':                   'item/majestic_leap.svg',
  'item/metal_skin':                      'item/metal_skin.svg',
  'item/rescue_beam':                     'item/rescue_beam.svg',
  'item/superior_stamina':                'item/superior_stamina.svg',
  'item/colossus':                        'item/colossus.svg',
  'item/inhibitor':                       'item/inhibitor.svg',
  'item/leech':                           'item/leech.svg',
  'item/phantom_strike':                  'item/phantom_strike.svg',
  'item/siphon_bullets':                  'item/siphon_bullets.svg',
  'item/unstoppable':                     'item/unstoppable.svg',
  'item/veil_walker':                     'item/veil_walker.svg',
  'item/ammo_scavenger':                  'item/ammo_scavenger.svg',
  'item/extra_charge':                    'item/extra_charge.svg',
  'item/extra_spirit':                    'item/extra_spirit.svg',
  'item/infuser':                         'item/infuser.svg',
  'item/mystic_burst':                    'item/mystic_burst.svg',
  'item/mystic_reach':                    'item/mystic_reach.svg',
  'item/spirit_strike':                   'item/spirit_strike.svg',
  'item/bullet_resist_shredder':          'item/bullet_resist_shredder.svg',
  'item/cold_front':                      'item/cold_front.svg',
  'item/decay':                           'item/decay.svg',
  'item/duration_extender':               'item/duration_extender.svg',
  'item/improved_cooldown':               'item/improved_cooldown.svg',
  'item/mystic_vulnerability':            'item/mystic_vulnerability.svg',
  'item/quicksilver_reload':              'item/quicksilver_reload.svg',
  'item/slowing_hex':                     'item/slowing_hex.svg',
  'item/suppressor':                      'item/suppressor.svg',
  'item/withering_whip':                  'item/withering_whip.svg',
  'item/arcane_surge':                    'item/arcane_surge.png',
  'item/ethereal_shift':                  'item/ethereal_shift.svg',
  'item/improved_burst':                  'item/improved_burst.svg',
  'item/improved_reach':                  'item/improved_reach.svg',
  'item/improved_spirit':                 'item/improved_spirit.svg',
  'item/knockdown':                       'item/knockdown.svg',
  'item/mystic_slow':                     'item/mystic_slow.svg',
  'item/rapid_recharge':                  'item/rapid_recharge.svg',
  'item/silence_glyph':                   'item/silence_glyph.svg',
  'item/spirit_snatch':                   'item/spirit_snatch.png',
  'item/superior_cooldown':               'item/superior_cooldown.svg',
  'item/superior_duration':               'item/superior_duration.svg',
  'item/surge_of_power':                  'item/surge_of_power.svg',
  'item/torment_pulse':                   'item/torment_pulse.svg',
  'item/boundless_spirit':                'item/boundless_spirit.svg',
  'item/curse':                           'item/curse.svg',
  'item/diviners_kevlar':                 'item/diviners_kevlar.svg',
  'item/echo_shard':                      'item/echo_shard.svg',
  'item/escalating_exposure':             'item/escalating_exposure.svg',
  'item/magic_carpet':                    'item/magic_carpet.svg',
  'item/mystic_reverb':                   'item/mystic_reverb.svg',
  'item/refresher':                       'item/refresher.svg',

  'legacy/hero/abrams/infernal_resilience_v1':      'legacy/hero/abrams/infernal_resilience_v1.svg',
  'legacy/hero/abrams/seismic_impact_v1':           'legacy/hero/abrams/seismic_impact_v1.svg',
  'legacy/hero/abrams/shoulder_charge_v1':          'legacy/hero/abrams/shoulder_charge_v1.svg',
  'legacy/hero/abrams/siphon_life_v1':              'legacy/hero/abrams/siphon_life_v1.svg',
  'legacy/hero/bebop/exploding_uppercut_v1':        'legacy/hero/bebop/exploding_uppercut_v1.svg',
  'legacy/hero/bebop/hyper_beam_v1':                'legacy/hero/bebop/hyper_beam_v1.svg',
  'legacy/hero/bebop/sticky_bomb_v1':               'legacy/hero/bebop/sticky_bomb_v1.svg',
  'legacy/hero/dynamo/kinetic_pulse_v1':            'legacy/hero/dynamo/kinetic_pulse_v1.svg',
  'legacy/hero/dynamo/quantum_entanglement_v1':     'legacy/hero/dynamo/quantum_entanglement_v1.svg',
  'legacy/hero/dynamo/rejuvenating_aurora_v1':      'legacy/hero/dynamo/rejuvenating_aurora_v1.svg',
  'legacy/hero/dynamo/singularity_v1':              'legacy/hero/dynamo/singularity_v1.svg',
  'legacy/hero/grey_talon/charged_shot_v1':         'legacy/hero/grey_talon/charged_shot_v1.svg',
  'legacy/hero/grey_talon/guided_owl_v1':           'legacy/hero/grey_talon/guided_owl_v1.svg',
  'legacy/hero/grey_talon/spirit_snare_v1':         'legacy/hero/grey_talon/spirit_snare_v1.svg',
  'legacy/hero/grey_talon/rain_of_arrows_v1':       'legacy/hero/grey_talon/rain_of_arrows_v1.svg',
  'legacy/hero/haze/bullet_dance_v1':               'legacy/hero/haze/bullet_dance_v1.svg',
  'legacy/hero/haze/fixation_v1':                   'legacy/hero/haze/fixation_v1.svg',
  'legacy/hero/haze/sleep_dagger_v1':               'legacy/hero/haze/sleep_dagger_v1.svg',
  'legacy/hero/haze/smoke_bomb_v1':                 'legacy/hero/haze/smoke_bomb_v1.svg',
  'legacy/hero/infernus/afterburn_v1':              'legacy/hero/infernus/afterburn_v1.svg',
  'legacy/hero/infernus/catalyst_v1':               'legacy/hero/infernus/catalyst_v1.svg',
  'legacy/hero/infernus/concussive_combustion_v1':  'legacy/hero/infernus/concussive_combustion_v1.svg',
  'legacy/hero/infernus/flame_dash_v1':             'legacy/hero/infernus/flame_dash_v1.svg',
  'legacy/hero/ivy/air_drop_v1':                    'legacy/hero/ivy/air_drop_v1.svg',
  'legacy/hero/ivy/kudzu_bomb_v1':                  'legacy/hero/ivy/kudzu_bomb_v1.svg',
  'legacy/hero/ivy/stone_form_v1':                  'legacy/hero/ivy/stone_form_v1.svg',
  'legacy/hero/ivy/watchers_covenant_v1':           'legacy/hero/ivy/watchers_covenant_v1.svg',
  'legacy/hero/kelvin/arctic_beam_v1':              'legacy/hero/kelvin/arctic_beam_v1.svg',
  'legacy/hero/kelvin/frost_grenade_v1':            'legacy/hero/kelvin/frost_grenade_v1.svg',
  'legacy/hero/kelvin/frozen_shelter_v1':           'legacy/hero/kelvin/frozen_shelter_v1.svg',
  'legacy/hero/kelvin/ice_path_v1':                 'legacy/hero/kelvin/ice_path_v1.svg',
  'legacy/hero/lady_geist/essence_bomb_v1':         'legacy/hero/lady_geist/essence_bomb_v1.svg',
  'legacy/hero/lady_geist/life_drain_v1':           'legacy/hero/lady_geist/life_drain_v1.svg',
  'legacy/hero/lady_geist/malice_v1':               'legacy/hero/lady_geist/malice_v1.svg',
  'legacy/hero/lady_geist/soul_exchange_v1':        'legacy/hero/lady_geist/soul_exchange_v1.svg',
  'legacy/hero/lash/death_slam_v1':                 'legacy/hero/lash/death_slam_v1.svg',
  'legacy/hero/lash/flog_v1':                       'legacy/hero/lash/flog_v1.svg',
  'legacy/hero/lash/grapple_v1':                    'legacy/hero/lash/grapple_v1.svg',
  'legacy/hero/lash/ground_strike_v1':              'legacy/hero/lash/ground_strike_v1.svg',
  'legacy/hero/mcginnis/spectral_wall_v1':          'legacy/hero/mcginnis/spectral_wall_v1.svg',
  'legacy/hero/mirage/djinns_mark_v1':              'legacy/hero/mirage/djinns_mark_v1.svg',
  'legacy/hero/mirage/fire_scarabs_v1':             'legacy/hero/mirage/fire_scarabs_v1.svg',
  'legacy/hero/mirage/traveler_v1':                 'legacy/hero/mirage/traveler_v1.svg',
  'legacy/hero/mo_and_krill/burrow_v1':             'legacy/hero/mo_and_krill/burrow_v1.svg',
  'legacy/hero/mo_and_krill/sand_blast_v1':         'legacy/hero/mo_and_krill/sand_blast_v1.svg',
  'legacy/hero/mo_and_krill/scorn_v1':              'legacy/hero/mo_and_krill/scorn_v1.svg',
  'legacy/hero/paradox/paradoxical_swap_v1':        'legacy/hero/paradox/paradoxical_swap_v1.svg',
  'legacy/hero/paradox/pulse_grenade_v1':           'legacy/hero/paradox/pulse_grenade_v1.svg',
  'legacy/hero/paradox/time_wall_v1':               'legacy/hero/paradox/time_wall_v1.svg',
  'legacy/hero/pocket/affliction_v1':               'legacy/hero/pocket/affliction_v1.svg',
  'legacy/hero/pocket/barrage_v1':                  'legacy/hero/pocket/barrage_v1.svg',
  'legacy/hero/pocket/enchanters_satchel_v1':       'legacy/hero/pocket/enchanters_satchel_v1.svg',
  'legacy/hero/pocket/flying_cloak_v1':             'legacy/hero/pocket/flying_cloak_v1.svg',
  'legacy/hero/seven/lightning_ball_v1':            'legacy/hero/seven/lightning_ball_v1.svg',
  'legacy/hero/seven/power_surge_v1':               'legacy/hero/seven/power_surge_v1.svg',
  'legacy/hero/seven/static_charge_v1':             'legacy/hero/seven/static_charge_v1.svg',
  'legacy/hero/seven/storm_cloud_v1':               'legacy/hero/seven/storm_cloud_v1.svg',
  'legacy/hero/shiv/bloodletting_v1':               'legacy/hero/shiv/bloodletting_v1.svg',
  'legacy/hero/shiv/killing_blow_v1':               'legacy/hero/shiv/killing_blow_v1.svg',
  'legacy/hero/shiv/serrated_knives_v1':            'legacy/hero/shiv/serrated_knives_v1.svg',
  'legacy/hero/shiv/slice_and_dice_v1':             'legacy/hero/shiv/slice_and_dice_v1.svg',
  'legacy/hero/vindicta/assassinate_v1':            'legacy/hero/vindicta/assassinate_v1.svg',
  'legacy/hero/vindicta/crow_familiar_v1':          'legacy/hero/vindicta/crow_familiar_v1.svg',
  'legacy/hero/vindicta/flight_v1':                 'legacy/hero/vindicta/flight_v1.svg',
  'legacy/hero/vindicta/stake_v1':                  'legacy/hero/vindicta/stake_v1.svg',
  'legacy/hero/viscous/goo_ball_v1':                'legacy/hero/viscous/goo_ball_v1.svg',
  'legacy/hero/viscous/puddle_punch_v1':            'legacy/hero/viscous/puddle_punch_v1.svg',
  'legacy/hero/viscous/splatter_v1':                'legacy/hero/viscous/splatter_v1.svg',
  'legacy/hero/viscous/the_cube_v1':                'legacy/hero/viscous/the_cube_v1.svg',
  'legacy/hero/warden/alchemical_flask_v1':         'legacy/hero/warden/alchemical_flask_v1.svg',
  'legacy/hero/warden/binding_word_v1':             'legacy/hero/warden/binding_word_v1.svg',
  'legacy/hero/warden/last_stand_v1':               'legacy/hero/warden/last_stand_v1.svg',
  'legacy/hero/warden/willpower_v1':                'legacy/hero/warden/willpower_v1.svg',
  'legacy/hero/wraith/full_auto_v1':                'legacy/hero/wraith/full_auto_v1.svg',
  'legacy/hero/wraith/project_mind_v1':             'legacy/hero/wraith/project_mind_v1.svg',
  'legacy/hero/yamato/crimson_slash_v1':            'legacy/hero/yamato/crimson_slash_v1.svg',
  'legacy/hero/yamato/flying_strike_v1':            'legacy/hero/yamato/flying_strike_v1.svg',
  'legacy/hero/yamato/power_slash_v1':              'legacy/hero/yamato/power_slash_v1.svg',
  'legacy/hero/yamato/shadow_transformation_v1':    'legacy/hero/yamato/shadow_transformation_v1.svg',

  'hero/abrams/infernal_resilience':      'hero/abrams/infernal_resilience.png',
  'hero/abrams/seismic_impact':           'hero/abrams/seismic_impact.png',
  'hero/abrams/shoulder_charge':          'hero/abrams/shoulder_charge.png',
  'hero/abrams/siphon_life':              'hero/abrams/siphon_life.png',
  'hero/bebop/exploding_uppercut':        'hero/bebop/exploding_uppercut.png',
  'hero/bebop/hook':                      'hero/bebop/hook.svg',
  'hero/bebop/hyper_beam':                'hero/bebop/hyper_beam.png',
  'hero/bebop/sticky_bomb':               'hero/bebop/sticky_bomb.png',
  'hero/billy/bashdown':                  'hero/billy/bashdown.png',
  'hero/billy/blasted':                   'hero/billy/blasted.png',
  'hero/billy/chain_gang':                'hero/billy/chain_gang.png',
  'hero/billy/rising_ram':                'hero/billy/rising_ram.png',
  'hero/calico/ava':                      'hero/calico/ava.png',
  'hero/calico/gloom_bombs':              'hero/calico/gloom_bombs.png',
  'hero/calico/leaping_slash':            'hero/calico/leaping_slash.png',
  'hero/calico/return_to_shadows':        'hero/calico/return_to_shadows.png',
  'hero/doorman/call_bell':               'hero/doorman/call_bell.png',
  'hero/doorman/doorway':                 'hero/doorman/doorway.png',
  'hero/doorman/hotel_guest':             'hero/doorman/hotel_guest.png',
  'hero/doorman/luggage_cart':            'hero/doorman/luggage_cart.png',
  'hero/drifter/bloodscent':              'hero/drifter/bloodscent.png',
  'hero/drifter/eternal_night':           'hero/drifter/eternal_night.png',
  'hero/drifter/rend':                    'hero/drifter/rend.png',
  'hero/drifter/stalkers_mark':           'hero/drifter/stalkers_mark.png',
  'hero/dynamo/kinetic_pulse':            'hero/dynamo/kinetic_pulse.png',
  'hero/dynamo/quantum_entanglement':     'hero/dynamo/quantum_entanglement.png',
  'hero/dynamo/rejuvenating_aurora':      'hero/dynamo/rejuvenating_aurora.png',
  'hero/dynamo/singularity':              'hero/dynamo/singularity.png',
  'hero/graves/borrowed_decree':          'hero/graves/borrowed_decree.png',
  'hero/graves/essence_theft':            'hero/graves/essence_theft.png',
  'hero/graves/grasping_hands':           'hero/graves/grasping_hands.png',
  'hero/graves/jar_of_dead':              'hero/graves/jar_of_dead.png',
  'hero/grey_talon/charged_shot':         'hero/grey_talon/charged_shot.png',
  'hero/grey_talon/guided_owl':           'hero/grey_talon/guided_owl.png',
  'hero/grey_talon/spirit_snare':         'hero/grey_talon/spirit_snare.png',
  'hero/grey_talon/rain_of_arrows':       'hero/grey_talon/rain_of_arrows.png',
  'hero/haze/bullet_dance':               'hero/haze/bullet_dance.png',
  'hero/haze/fixation':                   'hero/haze/fixation.png',
  'hero/haze/sleep_dagger':               'hero/haze/sleep_dagger.png',
  'hero/haze/smoke_bomb':                 'hero/haze/smoke_bomb.png',
  'hero/holliday/bounce_pad':             'hero/holliday/bounce_pad.png',
  'hero/holliday/crackshot':              'hero/holliday/crackshot.png',
  'hero/holliday/powder_key':             'hero/holliday/powder_key.png',
  'hero/holliday/spirit_lasso':           'hero/holliday/spirit_lasso.png',
  'hero/infernus/afterburn':              'hero/infernus/afterburn.png',
  'hero/infernus/napalm':                 'hero/infernus/napalm.png',
  'hero/infernus/concussive_combustion':  'hero/infernus/concussive_combustion.png',
  'hero/infernus/flame_dash':             'hero/infernus/flame_dash.png',
  'hero/ivy/air_drop':                    'hero/ivy/air_drop.png',
  'hero/ivy/kudzu_bomb':                  'hero/ivy/kudzu_bomb.png',
  'hero/ivy/stone_form':                  'hero/ivy/stone_form.png',
  'hero/ivy/watchers_covenant':           'hero/ivy/watchers_covenant.png',
  'hero/kelvin/arctic_beam':              'hero/kelvin/arctic_beam.png',
  'hero/kelvin/frost_grenade':            'hero/kelvin/frost_grenade.png',
  'hero/kelvin/frozen_shelter':           'hero/kelvin/frozen_shelter.png',
  'hero/kelvin/ice_path':                 'hero/kelvin/ice_path.png',
  'hero/lady_geist/essence_bomb':         'hero/lady_geist/essence_bomb.png',
  'hero/lady_geist/life_drain':           'hero/lady_geist/life_drain.png',
  'hero/lady_geist/malice':               'hero/lady_geist/malice.png',
  'hero/lady_geist/soul_exchange':        'hero/lady_geist/soul_exchange.png',
  'hero/lash/death_slam':                 'hero/lash/death_slam.png',
  'hero/lash/flog':                       'hero/lash/flog.png',
  'hero/lash/grapple':                    'hero/lash/grapple.png',
  'hero/lash/ground_strike':              'hero/lash/ground_strike.png',
  'hero/mcginnis/heavy_barrage':          'hero/mcginnis/heavy_barrage.svg',
  'hero/mcginnis/medicinal_specter':      'hero/mcginnis/medicinal_specter.svg',
  'hero/mcginnis/mini_turret':            'hero/mcginnis/mini_turret.svg',
  'hero/mcginnis/spectral_wall':          'hero/mcginnis/spectral_wall.png',
  'hero/mina/love_bites':                 'hero/mina/love_bites.png',
  'hero/mina/nox_nostra':                 'hero/mina/nox_nostra.png',
  'hero/mina/rake':                       'hero/mina/rake.png',
  'hero/mina/sanguine_retreat':           'hero/mina/sanguine_retreat.png',
  'hero/mirage/djinns_mark':              'hero/mirage/djinns_mark.png',
  'hero/mirage/fire_scarabs':             'hero/mirage/fire_scarabs.png',
  'hero/mirage/tornado':                  'hero/mirage/tornado.svg',
  'hero/mirage/traveler':                 'hero/mirage/traveler.png',
  'hero/mo_and_krill/burrow':             'hero/mo_and_krill/burrow.png',
  'hero/mo_and_krill/combo':              'hero/mo_and_krill/combo.svg',
  'hero/mo_and_krill/sand_blast':         'hero/mo_and_krill/sand_blast.png',
  'hero/mo_and_krill/scorn':              'hero/mo_and_krill/scorn.png',
  'hero/paige/captivating_read':          'hero/paige/captivating_read.png',
  'hero/paige/conjure_dragon':            'hero/paige/conjure_dragon.png',
  'hero/paige/defend_and_fight':          'hero/paige/defend_and_fight.png',
  'hero/paige/rallying_charge':           'hero/paige/rallying_charge.png',
  'hero/paradox/kinetic_carbine':         'hero/paradox/kinetic_carbine.svg',
  'hero/paradox/paradoxical_swap':        'hero/paradox/paradoxical_swap.png',
  'hero/paradox/pulse_grenade':           'hero/paradox/pulse_grenade.png',
  'hero/paradox/time_wall':               'hero/paradox/time_wall.png',
  'hero/pocket/affliction':               'hero/pocket/affliction.png',
  'hero/pocket/barrage':                  'hero/pocket/barrage.png',
  'hero/pocket/enchanters_satchel':       'hero/pocket/enchanters_satchel.png',
  'hero/pocket/flying_cloak':             'hero/pocket/flying_cloak.png',
  'hero/rem/lil_helpers':                 'hero/rem/lil_helpers.png',
  'hero/rem/naptime':                     'hero/rem/naptime.png',
  'hero/rem/pillow_toss':                 'hero/rem/pillow_toss.png',
  'hero/rem/tag_along':                   'hero/rem/tag_along.png',
  'hero/seven/lightning_ball':            'hero/seven/lightning_ball.png',
  'hero/seven/power_surge':               'hero/seven/power_surge.png',
  'hero/seven/static_charge':             'hero/seven/static_charge.png',
  'hero/seven/storm_cloud':               'hero/seven/storm_cloud.png',
  'hero/shiv/bloodletting':               'hero/shiv/bloodletting.png',
  'hero/shiv/killing_blow':               'hero/shiv/killing_blow.png',
  'hero/shiv/serrated_knives':            'hero/shiv/serrated_knives.png',
  'hero/shiv/slice_and_dice':             'hero/shiv/slice_and_dice.png',
  'hero/silver/boot_kick':                'hero/silver/boot_kick.png',
  'hero/silver/entangling_bola':          'hero/silver/entangling_bola.png',
  'hero/silver/lycan_curse':              'hero/silver/lycan_curse.png',
  'hero/silver/slam_fire':                'hero/silver/slam_fire.png',
  'hero/sinclair/audience_participation': 'hero/sinclair/audience_participation.png',
  'hero/sinclair/rabbit_hex':             'hero/sinclair/rabbit_hex.png',
  'hero/sinclair/spectral_assistant':     'hero/sinclair/spectral_assistant.png',
  'hero/sinclair/vexing_bolt':            'hero/sinclair/vexing_bolt.png',
  'hero/venator/consecrating_grenade':    'hero/venator/consecrating_grenade.png',
  'hero/venator/gutshot':                 'hero/venator/gutshot.png',
  'hero/venator/hex_lined_snap_trap':     'hero/venator/hex_lined_snap_trap.png',
  'hero/venator/ira_domini':              'hero/venator/ira_domini.png',
  'hero/victor/aura_of_suffering':        'hero/victor/aura_of_suffering.png',
  'hero/victor/jumpstart':                'hero/victor/jumpstart.png',
  'hero/victor/pain_battery':             'hero/victor/pain_battery.png',
  'hero/victor/shocking_reanimation':     'hero/victor/shocking_reanimation.png',
  'hero/vindicta/assassinate':            'hero/vindicta/assassinate.png',
  'hero/vindicta/crow_familiar':          'hero/vindicta/crow_familiar.png',
  'hero/vindicta/flight':                 'hero/vindicta/flight.png',
  'hero/vindicta/stake':                  'hero/vindicta/stake.png',
  'hero/viscous/goo_ball':                'hero/viscous/goo_ball.png',
  'hero/viscous/puddle_punch':            'hero/viscous/puddle_punch.png',
  'hero/viscous/splatter':                'hero/viscous/splatter.png',
  'hero/viscous/the_cube':                'hero/viscous/the_cube.png',
  'hero/vyper/lethal_venom':              'hero/vyper/lethal_venom.png',
  'hero/vyper/petrifying_bola':           'hero/vyper/petrifying_bola.png',
  'hero/vyper/screwjab_dagger':           'hero/vyper/screwjab_dagger.png',
  'hero/vyper/slither':                   'hero/vyper/slither.png',
  'hero/warden/alchemical_flask':         'hero/warden/alchemical_flask.png',
  'hero/warden/binding_word':             'hero/warden/binding_word.png',
  'hero/warden/last_stand':               'hero/warden/last_stand.png',
  'hero/warden/willpower':                'hero/warden/willpower.png',
  'hero/wraith/card_trick':               'hero/wraith/card_trick.svg',
  'hero/wraith/full_auto':                'hero/wraith/full_auto.png',
  'hero/wraith/project_mind':             'hero/wraith/project_mind.png',
  'hero/wraith/telekinesis':              'hero/wraith/telekinesis.svg',
  'hero/yamato/crimson_slash':            'hero/yamato/crimson_slash.png',
  'hero/yamato/flying_strike':            'hero/yamato/flying_strike.png',
  'hero/yamato/power_slash':              'hero/yamato/power_slash.png',
  'hero/yamato/shadow_transformation':    'hero/yamato/shadow_transformation.png',

  'stat/cooldown':                        'stat/cooldown.svg',
  'stat/charge':                          'stat/charge.svg',
  'stat/charge_cooldown':                 'stat/charge_cooldown.svg',
  'stat/duration':                        'stat/duration.svg',
  'stat/range':                           'stat/range.svg',
  'stat/aoe':                             'stat/aoe.svg',
  'stat/weapon_damage':                   'stat/weapon_damage.svg',
  'stat/spirit_damage':                   'stat/spirit_damage.svg',
  'stat/melee':                           'stat/melee.svg',
  'stat/bullet':                          'stat/bullet.svg',
  'stat/fire_rate':                       'stat/fire_rate.svg',
  'stat/ammo':                            'stat/ammo.svg',
  'stat/reload':                          'stat/reload.svg',
  'stat/bullet_armor':                    'stat/bullet_armor.svg',
  'stat/bullet_resist_reduction':         'stat/bullet_resist_reduction.png',
  'stat/spirit_armor':                    'stat/spirit_armor.svg',
  'stat/spirit_resist_reduction':         'stat/spirit_resist_reduction.png',
  'stat/bullet_shield':                   'stat/bullet_shield.svg',
  'stat/spirit_shield':                   'stat/spirit_shield.svg',
  'stat/move_speed':                      'stat/move_speed.svg',
  'stat/stamina':                         'stat/stamina.svg',
  'stat/move_slow':                       'stat/move_slow.svg',
  'stat/stun':                            'stat/stun.svg',
  'stat/invisible':                       'stat/invisible.svg',
  'stat/health':                          'stat/health.svg',
  'stat/healing':                         'stat/healing.svg',
  'stat/damage_amplification':            'stat/damage_amplification.svg',
  'stat/placeholder':                     'stat/placeholder.svg',
  'stat/ability_point':                   'stat/ability_point.svg',
  'stat/silence':                         'stat/silence.svg',
  'boon_scaling':                         'boon_scaling.png',
  'cancel':                               'cancel.svg',
  'compress':                             'compress.svg',
  'dropdown':                             'dropdown.svg',
  'error':                                'error.svg',
  'expand':                               'expand.svg',
  'font':                                 'font.svg',
  'gear':                                 'gear.svg',
  'grip':                                 'grip.svg',
  'hourglass_half':                       'hourglass_half.svg',
  'plus':                                 'plus.svg',
  'soul':                                 'soul.svg',
  'spirit':                               'spirit.svg',
  'swap':                                 'swap.svg',
  'trash':                                'trash.svg',
  'vitality':                             'vitality.svg',
  'weapon':                               'weapon.svg',
};

const allIconFiles = Object.values(filenames);

const dataRegex = /^data:/;
const isData = (s) => Boolean(s.match(dataRegex));

const Icon = ({image, large, color, onMouseDown}) => {
  const config = useContext(ConfigContext);
  const colorClass = `mock-icon-${color}`;
  const classes = classNames('mock-icon', {
    [colorClass]:          Boolean(color),
    'mock-icon-clickable': Boolean(onMouseDown),
    'mock-icon-large':     Boolean(large),
  });

  const filename = filenames[image] || filenames['stat/placeholder'];
  const url = image && isData(image) ?
    `url(${image})` :
    `url("${config.baseUrl}icon/${filename}")`;

  return (
    <span
      className={classes}
      style={{maskImage: url}}
      onMouseDown={onMouseDown}
    />
  );
};

export {Icon, allIconFiles, hiddenColors, iconColors};
