import {action} from 'mobx';
import {useCallback} from 'preact/hooks';

// eslint-disable-next-line react-hooks/exhaustive-deps
const useAction = (cb, deps) => useCallback(action(cb), deps);

const deepCopy = (x) => JSON.parse(JSON.stringify(x));

const WEAPON_CATEGORY = 'weapon';
const VITALITY_CATEGORY = 'vitality';
const SPIRIT_CATEGORY = 'spirit';

const items = {
  'Basic Magazine':         {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/basic_magazine'},
  'Close Quarters':         {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/close_quarters'},
  'Headshot Booster':       {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/headshot_booster'},
  'High-Velocity Mag':      {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/high_velocity_mag'},
  'Hollow Point Ward':      {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/hollow_point_ward'},
  'Monster Rounds':         {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/monster_rounds'},
  'Rapid Rounds':           {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/rapid_rounds'},
  'Restorative Shot':       {tier: 1, cost:  500, category: WEAPON_CATEGORY, icon: 'item/restorative_shot'},
  'Active Reload':          {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/active_reload'},
  'Berserker':              {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/berserker'},
  'Fleetfoot':              {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/fleetfoot'},
  'Kinetic Dash':           {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/kinetic_dash'},
  'Long Range':             {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/long_range'},
  'Melee Charge':           {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/melee_charge'},
  'Mystic Shot':            {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/mystic_shot'},
  'Slowing Bullets':        {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/slowing_bullets'},
  'Soul Shredder Bullets':  {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/soul_shredder_bullets'},
  'Swift Striker':          {tier: 2, cost: 1250, category: WEAPON_CATEGORY, icon: 'item/swift_striker'},
  'Alchemical Fire':        {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/alchemical_fire'},
  'Burst Fire':             {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/burst_fire'},
  'Escalating Resilience':  {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/escalating_resilience'},
  'Headhunter':             {tier: 3, cost: 3500, category: WEAPON_CATEGORY, icon: 'item/headhunter'},
  'Heroic Aura':            {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/heroic_aura'},
  'Hunter\'s Aura':         {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/hunters_aura'},
  'Intensifying Magazine':  {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/intensifying_magazine'},
  'Point Blank':            {tier: 3, cost: 3500, category: WEAPON_CATEGORY, icon: 'item/point_blank'},
  'Pristine Emblem':        {tier: 3, cost: 3500, category: WEAPON_CATEGORY, icon: 'item/pristine_emblem'},
  'Sharpshooter':           {tier: 3, cost: 4250, category: WEAPON_CATEGORY, icon: 'item/sharpshooter'},
  'Spellslinger Headshots': {tier: 3, cost: 4250, category: WEAPON_CATEGORY, icon: 'stat/placeholder'},
  'Tesla Bullets':          {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/tesla_bullets'},
  'Titanic Magazine':       {tier: 3, cost: 3500, category: WEAPON_CATEGORY, icon: 'item/titanic_magazine'},
  'Toxic Bullets':          {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/toxic_bullets'},
  'Warp Stone':             {tier: 3, cost: 3000, category: WEAPON_CATEGORY, icon: 'item/warp_stone'},
  'Crippling Headshot':     {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/crippling_headshot'},
  'Frenzy':                 {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/frenzy'},
  'Glass Cannon':           {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/glass_cannon'},
  'Lucky Shot':             {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/lucky_shot'},
  'Ricochet':               {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/ricochet'},
  'Shadow Weave':           {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/shadow_weave'},
  'Silencer':               {tier: 4, cost: 7450, category: WEAPON_CATEGORY, icon: 'item/silencer'},
  'Spiritual Overflow':     {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/spiritual_overflow'},
  'Vampiric Burst':         {tier: 4, cost: 6200, category: WEAPON_CATEGORY, icon: 'item/vampiric_burst'},

  'Enduring Spirit':        {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/enduring_spirit'},
  'Extra Health':           {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/extra_health'},
  'Extra Regen':            {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/extra_regen'},
  'Extra Stamina':          {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/extra_stamina'},
  'Healing Rite':           {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/healing_rite'},
  'Melee Lifesteal':        {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/melee_lifesteal'},
  'Sprint Boots':           {tier: 1, cost:  500, category: VITALITY_CATEGORY, icon: 'item/sprint_boots'},
  'Bullet Armor':           {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/bullet_armor'},
  'Bullet Lifesteal':       {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/bullet_lifesteal'},
  'Combat Barrier':         {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/combat_barrier'},
  'Debuff Reducer':         {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/debuff_reducer'},
  'Divine Barrier':         {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/divine_barrier'},
  'Enchanter\'s Barrier':   {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/enchanters_barrier'},
  'Enduring Speed':         {tier: 2, cost: 1750, category: VITALITY_CATEGORY, icon: 'item/enduring_speed'},
  'Healbane':               {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/healbane'},
  'Healing Booster':        {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/healing_booster'},
  'Healing Nova':           {tier: 2, cost: 1750, category: VITALITY_CATEGORY, icon: 'item/healing_nova'},
  'Reactive Barrier':       {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/reactive_barrier'},
  'Restorative Locket':     {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/restorative_locket'},
  'Return Fire':            {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/return_fire'},
  'Spirit Armor':           {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/spirit_armor'},
  'Spirit Lifesteal':       {tier: 2, cost: 1250, category: VITALITY_CATEGORY, icon: 'item/spirit_lifesteal'},
  'Debuff Remover':         {tier: 3, cost: 4250, category: VITALITY_CATEGORY, icon: 'item/debuff_remover'},
  'Fortitude':              {tier: 3, cost: 3500, category: VITALITY_CATEGORY, icon: 'item/fortitude'},
  'Improved Bullet Armor':  {tier: 3, cost: 4250, category: VITALITY_CATEGORY, icon: 'item/improved_bullet_armor'},
  'Improved Spirit Armor':  {tier: 3, cost: 4250, category: VITALITY_CATEGORY, icon: 'item/improved_spirit_armor'},
  'Lifestrike':             {tier: 3, cost: 3500, category: VITALITY_CATEGORY, icon: 'item/lifestrike'},
  'Majestic Leap':          {tier: 3, cost: 3000, category: VITALITY_CATEGORY, icon: 'item/majestic_leap'},
  'Metal Skin':             {tier: 3, cost: 3000, category: VITALITY_CATEGORY, icon: 'item/metal_skin'},
  'Rescue Beam':            {tier: 3, cost: 3000, category: VITALITY_CATEGORY, icon: 'item/rescue_beam'},
  'Superior Stamina':       {tier: 3, cost: 3500, category: VITALITY_CATEGORY, icon: 'item/superior_stamina'},
  'Veil Walker':            {tier: 3, cost: 3000, category: VITALITY_CATEGORY, icon: 'item/veil_walker'},
  'Colossus':               {tier: 4, cost: 6200, category: VITALITY_CATEGORY, icon: 'item/colossus'},
  'Inhibitor':              {tier: 4, cost: 6200, category: VITALITY_CATEGORY, icon: 'item/inhibitor'},
  'Leech':                  {tier: 4, cost: 6200, category: VITALITY_CATEGORY, icon: 'item/leech'},
  'Phantom Strike':         {tier: 4, cost: 6200, category: VITALITY_CATEGORY, icon: 'item/phantom_strike'},
  'Siphon Bullets':         {tier: 4, cost: 6200, category: VITALITY_CATEGORY, icon: 'item/siphon_bullets'},
  'Unstoppable':            {tier: 4, cost: 6200, category: VITALITY_CATEGORY, icon: 'item/unstoppable'},

  'Ammo Scavenger':         {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/ammo_scavenger'},
  'Extra Charge':           {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/extra_charge'},
  'Extra Spirit':           {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/extra_spirit'},
  'Infuser':                {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/infuser'},
  'Mystic Burst':           {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/mystic_burst'},
  'Mystic Reach':           {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/mystic_reach'},
  'Spirit Strike':          {tier: 1, cost:  500, category: SPIRIT_CATEGORY, icon: 'item/spirit_strike'},
  'Bullet Resist Shredder': {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/bullet_resist_shredder'},
  'Cold Front':             {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/cold_front'},
  'Decay':                  {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/decay'},
  'Duration Extender':      {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/duration_extender'},
  'Improved Cooldown':      {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/improved_cooldown'},
  'Mystic Vulnerability':   {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/mystic_vulnerability'},
  'Quicksilver Reload':     {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/quicksilver_reload'},
  'Slowing Hex':            {tier: 2, cost: 1750, category: SPIRIT_CATEGORY, icon: 'item/slowing_hex'},
  'Suppressor':             {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/suppressor'},
  'Withering Whip':         {tier: 2, cost: 1250, category: SPIRIT_CATEGORY, icon: 'item/withering_whip'},
  'Arcane Surge':           {tier: 3, cost: 4250, category: SPIRIT_CATEGORY, icon: 'stat/placeholder'},
  'Ethereal Shift':         {tier: 3, cost: 3000, category: SPIRIT_CATEGORY, icon: 'item/ethereal_shift'},
  'Improved Burst':         {tier: 3, cost: 3500, category: SPIRIT_CATEGORY, icon: 'item/improved_burst'},
  'Improved Reach':         {tier: 3, cost: 3500, category: SPIRIT_CATEGORY, icon: 'item/improved_reach'},
  'Improved Spirit':        {tier: 3, cost: 3500, category: SPIRIT_CATEGORY, icon: 'item/improved_spirit'},
  'Knockdown':              {tier: 3, cost: 3000, category: SPIRIT_CATEGORY, icon: 'item/knockdown'},
  'Mystic Slow':            {tier: 3, cost: 4250, category: SPIRIT_CATEGORY, icon: 'item/mystic_slow'},
  'Rapid Recharge':         {tier: 3, cost: 3500, category: SPIRIT_CATEGORY, icon: 'item/rapid_recharge'},
  'Silence Glyph':          {tier: 3, cost: 3000, category: SPIRIT_CATEGORY, icon: 'item/silence_glyph'},
  'Spirit Snatch':          {tier: 3, cost: 3500, category: SPIRIT_CATEGORY, icon: 'stat/placeholder'},
  'Superior Cooldown':      {tier: 3, cost: 4250, category: SPIRIT_CATEGORY, icon: 'item/superior_cooldown'},
  'Superior Duration':      {tier: 3, cost: 4250, category: SPIRIT_CATEGORY, icon: 'item/superior_duration'},
  'Surge of Power':         {tier: 3, cost: 3000, category: SPIRIT_CATEGORY, icon: 'item/surge_of_power'},
  'Torment Pulse':          {tier: 3, cost: 3000, category: SPIRIT_CATEGORY, icon: 'item/torment_pulse'},
  'Boundless Spirit':       {tier: 4, cost: 9700, category: SPIRIT_CATEGORY, icon: 'item/boundless_spirit'},
  'Curse':                  {tier: 4, cost: 6200, category: SPIRIT_CATEGORY, icon: 'item/curse'},
  'Diviner\'s Kevlar':      {tier: 4, cost: 6200, category: SPIRIT_CATEGORY, icon: 'item/diviners_kevlar'},
  'Echo Shard':             {tier: 4, cost: 6200, category: SPIRIT_CATEGORY, icon: 'item/echo_shard'},
  'Escalating Exposure':    {tier: 4, cost: 7450, category: SPIRIT_CATEGORY, icon: 'item/escalating_exposure'},
  'Magic Carpet':           {tier: 4, cost: 6200, category: SPIRIT_CATEGORY, icon: 'item/magic_carpet'},
  'Mystic Reverb':          {tier: 4, cost: 6200, category: SPIRIT_CATEGORY, icon: 'item/mystic_reverb'},
  'Refresher':              {tier: 4, cost: 6200, category: SPIRIT_CATEGORY, icon: 'item/refresher'},
};

// TODO: autogenerate these
const abilityIcons = [
  'hero/pocket/barrage',
  'hero/pocket/enchanters_satchel',
  'hero/pocket/affliction',
  'hero/pocket/flying_cloak',
  'hero/kelvin/frozen_shelter',
  'hero/kelvin/ice_path',
  'hero/kelvin/frost_grenade',
  'hero/kelvin/arctic_beam',
  'hero/lady_geist/soul_exchange',
  'hero/lady_geist/life_drain',
  'hero/lady_geist/essence_bomb',
  'hero/lady_geist/malice',
  'hero/lash/ground_strike',
  'hero/lash/death_slam',
  'hero/lash/grapple',
  'hero/lash/flog',
  'hero/abrams/siphon_life',
  'hero/abrams/shoulder_charge',
  'hero/abrams/seismic_impact',
  'hero/abrams/infernal_resilience',
  'hero/yamato/shadow_transformation',
  'hero/yamato/power_slash',
  'hero/yamato/flying_strike',
  'hero/yamato/crimson_slash',
  'hero/infernus/concussive_combustion',
  'hero/infernus/afterburn',
  'hero/infernus/catalyst',
  'hero/infernus/flame_dash',
  'hero/ivy/air_drop',
  'hero/ivy/stone_form',
  'hero/ivy/kudzu_bomb',
  'hero/ivy/watchers_covenant',
  'hero/viscous/splatter',
  'hero/viscous/puddle_punch',
  'hero/viscous/goo_ball',
  'hero/viscous/the_cube',
  'hero/vindicta/assassinate',
  'hero/vindicta/flight',
  'hero/vindicta/crow_familiar',
  'hero/vindicta/stake',
  'hero/dynamo/rejuvenating_aura',
  'hero/dynamo/kinetic_pulse',
  'hero/dynamo/quantum_entanglement',
  'hero/dynamo/singularity',
  'hero/mirage/traveler',
  'hero/mirage/tornado',
  'hero/mirage/djinns_mark',
  'hero/mirage/fire_scarabs',
  'hero/mcginnis/spectral_wall',
  'hero/mcginnis/mini_turret',
  'hero/mcginnis/medicinal_specter',
  'hero/mcginnis/heavy_barrage',
  'hero/grey_talon/immobilizing_trap',
  'hero/grey_talon/charged_shot',
  'hero/grey_talon/rain_of_arrows',
  'hero/grey_talon/guided_owl',
  'hero/bebop/hyper_beam',
  'hero/bebop/sticky_bomb',
  'hero/bebop/hook',
  'hero/bebop/exploding_uppercut',
  'hero/seven/power_surge',
  'hero/seven/lightning_ball',
  'hero/seven/static_charge',
  'hero/seven/storm_cloud',
  'hero/haze/bullet_dance',
  'hero/haze/fixation',
  'hero/haze/sleep_dagger',
  'hero/haze/smoke_bomb',
  'hero/paradox/pulse_grenade',
  'hero/paradox/time_wall',
  'hero/paradox/paradoxical_swap',
  'hero/paradox/kinetic_carbine',
  'hero/wraith/card_trick',
  'hero/wraith/telekinesis',
  'hero/wraith/project_mind',
  'hero/wraith/full_auto',
  'hero/shiv/bloodletting',
  'hero/shiv/serrated_knives',
  'hero/shiv/killing_blow',
  'hero/shiv/slice_and_dice',
  'hero/mo_and_krill/sand_blast',
  'hero/mo_and_krill/combo',
  'hero/mo_and_krill/scorn',
  'hero/mo_and_krill/burrow',
  'hero/warden/willpower',
  'hero/warden/alchemical_flask',
  'hero/warden/last_stand',
  'hero/warden/binding_word',
];

// TODO: autogenerate these, move into a subdirectory
const statIcons = [
  'stat/ability_point',
  'stat/ammo',
  'stat/aoe',
  'stat/bullet',
  'stat/bullet_armor',
  'stat/bullet_resist_reduction',
  'stat/charge',
  'stat/charge_cooldown',
  'stat/cooldown',
  'stat/damage_amplification',
  'stat/duration',
  'stat/fire_rate',
  'stat/healing',
  'stat/health',
  'stat/melee',
  'stat/move_speed',
  'stat/movement_slow',
  'stat/placeholder',
  'stat/range',
  'stat/reload',
  'stat/silence',
  'stat/spirit_armor',
  'stat/spirit_damage',
  'stat/spirit_resist_reduction',
  'stat/stamina',
  'stat/weapon_damage',
];

const tierCosts = [0, 500, 1250, 3000, 6200];

export {abilityIcons, deepCopy, items, statIcons, tierCosts, useAction};
